'\" t
.\"     Title: candybar
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/04/2014
.\"    Manual: Candybar Manual
.\"    Source: candybar
.\"  Language: English
.\"
.TH "CANDYBAR" "1" "05/04/2014" "candybar" "Candybar Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
candybar \- WebKit\-based status bar for tiling window managers
.SH "SYNOPSIS"
.sp
\fBcandybar\fR [\fB\-c\fR \fIconfig\-file\fR | \fB\-h\fR \fIheight\fR | \fB\-m\fR \fImonitor\fR | \fB\-p\fR \fIposition\fR | \fB\-t\fR \fItheme\-uri\fR]
.SH "DESCRIPTION"
.sp
\fBcandybar\fR displays a HTML\-based status bar in a WebKit web view\&. It provides a smooth looking status bar with CSS transitions and effects, and the possibility of having a transparent background with effects without a desktop compositor running\&.
.sp
Screenshots are available on the candybar wiki\&.
.SH "OPTIONS"
.PP
\fB\-c\fR \fIconfig\-file\fR
.RS 4
Read configuration options from the specified
\fIconfig\-file\fR\&. config\-file overrides
\fICANDYBAR_CONFIG_PATH\fR
and any system\-wide and per\-user configuration files\&. The file must exist and be valid JSON\&.
.RE
.PP
\fB\-h\fR \fIheight\fR
.RS 4
Set the height of the status bar in pixels\&.
.RE
.PP
\fB\-m\fR \fImonitor\fR
.RS 4
Define which monitor the status bar appears on\&.
.RE
.PP
\fB\-p\fR \fIposition\fR
.RS 4
Set the status bar position\&. Valid options are
\fItop\fR
and
\fIbottom\fR\&.
.RE
.PP
\fB\-t\fR \fItheme\-uri\fR
.RS 4
Set the URI for a theme HTML file\&. Must be a valid URI, i\&.e\&. local files must be prefixed with
\fIfile://\fR\&.
.RE
.SH "WINDOW MANAGER SUPPORT"
.PP
\fBbspwm\fR
.RS 4
supported; requires bspwm to be configured to reserve space with
\fIbspc config top_padding 24\fR\&.
.RE
.PP
\fBdwm\fR
.RS 4
supported; requires the dwm built\-in bar to be enabled and set to the same position and height as candybar, candybar will be placed on top of the dwm bar\&.
.RE
.PP
\fBi3\fR
.RS 4
supported; desktop support requires the
\fIdesktops_i3\fR
widget to be enabled instead of the default
\fIdesktops\fR
widget for desktop list support\&.
.RE
.PP
\fBmonsterwm\fR
.RS 4
supported
.RE
.PP
\fBqtile\fR
.RS 4
supported; requires a recent version, support for desktop EWMH properties was implemented in qtile revision 02fd471\&.
.RE
.SH "FILES"
.PP
\fI~/\&.config/candybar/config\&.json\fR
.RS 4
Per\-user configuration file\&. See
\fBcandybar\fR(5) for further details\&.
.RE
.PP
\fI/etc/xdg/candybar/config\&.json\fR
.RS 4
System\-wide configuration file\&. See
\fBcandybar\fR(5) for further details\&.
.RE
.SH "ENVIRONMENT"
.PP
\fICANDYBAR_CONFIG_PATH\fR
.RS 4
Full path of an alternate
\fIconfig\&.json\fR
file\&. This variable overrides any system\-wide and per\-user configuration files, but does not override the
\fB\-c\fR
command\-line argument\&. The file must exist and be valid JSON\&.
.RE
.SH "AUTHORS"
.sp
Kim Silkebækken <kim\&.silkebaekken@gmail\&.com>
.sp
See https://github\&.com/Lokaltog/candybar/graphs/contributors for a list of all contributors\&.
.SH "SEE ALSO"
.sp
\fBcandybar\fR(5)
