.TH "wkline" 5 "March 2014" "beta" "Configuration Files"

.SH "NAME"
config.json \- configuration file for customizing wkline

.SH "DESCRIPTION"
.B config.json
is a JSON file that defines the theme, enabled widgets and widget options for wkline.

TODO

.SH "EXAMPLES"
TODO

.SH "FILES"
.I /etc/xdg/wkline/config.json
.RS
System-wide configuration file.
.RE
.I ~/.config/wkline/config.json
.RS
Per-user configuration file.

.SH "ENVIRONMENT"
.IP WKLINE_CONFIG_PATH
Full path of an alternate \fIconfig.json\fP. The file must exist and be valid JSON.

.SH "AUTHOR"
Kim Silkebækken <kim.silkebaekken@gmail.com>

.SH "SEE ALSO"
.BR wkline (1)
