'\" t
.\"     Title: wkline
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 03/20/2014
.\"    Manual: Wkline Manual
.\"    Source: wkline
.\"  Language: English
.\"
.TH "WKLINE" "5" "03/20/2014" "wkline" "Wkline Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
wkline \- configuration file for customizing wkline
.SH "SYNOPSIS"
.sp
\fI~/\&.config/wkline/config\&.json\fR
.sp
\fI/etc/xdg/wkline/config\&.json\fR
.SH "DESCRIPTION"
.sp
\fBconfig\&.json\fR is a JSON file that defines the appearance, enabled widgets and widget options for \fBwkline\fR(1)\&.
.SS "Configurable Widget Options"
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBDefaults\fR
.RS 4
.PP
\fIbattery\fR
.RS 4
.TS
tab(:);
lt lt
lt lt.
T{
name
T}:T{
BAT0
T}
T{
refresh_interval
T}:T{
20
T}
.TE
.sp 1
.RE
.PP
\fIdatetime\fR
.RS 4
.TS
tab(:);
lt lt
lt lt
lt lt.
T{
date_format
T}:T{
"%Y\-%m\-%d"
T}
T{
time_format
T}:T{
"%H:%M:%S"
T}
T{
refresh_interval
T}:T{
1
T}
.TE
.sp 1
.RE
.PP
\fIemail_imap\fR
.RS 4
.TS
tab(:);
lt lt
lt lt
lt lt
lt lt
lt lt.
T{
address
T}:T{
imaps://imap\&.gmail\&.com:993/INBOX
T}
T{
username
T}:T{
blank
T}
T{
password
T}:T{
blank
T}
T{
ssl_verify
T}:T{
true
T}
T{
refresh_interval
T}:T{
60
T}
.TE
.sp 1
.RE
.PP
\fIexternal_ip\fR
.RS 4
.TS
tab(:);
lt lt
lt lt.
T{
address
T}:T{
http://ipv4\&.icanhazip\&.com
T}
T{
refresh_interval
T}:T{
3600
T}
.TE
.sp 1
.RE
.PP
\fImagick_background\fR
.RS 4
.TS
tab(:);
lt lt
lt lt
lt lt.
T{
blur_radius
T}:T{
0
T}
T{
brightness
T}:T{
100
T}
T{
saturation
T}:T{
100
T}
.TE
.sp 1
.RE
.PP
\fInow_playing_mpd\fR
.RS 4
.TS
tab(:);
lt lt
lt lt
lt lt
lt lt.
T{
host
T}:T{
localhost
T}
T{
port
T}:T{
6600
T}
T{
timeout
T}:T{
5000
T}
T{
update_interval
T}:T{
1000
T}
.TE
.sp 1
.RE
.PP
\fIvolume\fR
.RS 4
.TS
tab(:);
lt lt
lt lt.
T{
card
T}:T{
default
T}
T{
selem
T}:T{
Master
T}
.TE
.sp 1
.RE
.PP
\fIweather\fR
.RS 4
.TS
tab(:);
lt lt
lt lt
lt lt.
T{
location
T}:T{
blank
T}
T{
unit
T}:T{
c
T}
T{
refresh_interval
T}:T{
1800
T}
.TE
.sp 1
.RE
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBbattery\fR
.RS 4
.TS
tab(:);
lt lt
lt lt.
T{
.sp
\fIname\fR
T}:T{
.sp
UPower name for the battery device
T}
T{
.sp
\fIrefresh_interval\fR
T}:T{
.sp
How quickly to check level in seconds
T}
.TE
.sp 1
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBdatetime\fR
.RS 4
.TS
tab(:);
lt lt
lt lt
lt lt.
T{
.sp
\fIdate_format\fR
T}:T{
.sp
Date format\&. %Y, %m, %d are variables
T}
T{
.sp
\fItime_format\fR
T}:T{
.sp
Time format\&. %H, %M, %S are variables
T}
T{
.sp
\fIrefresh_interval\fR
T}:T{
.sp
How quickly to refresh in seconds
T}
.TE
.sp 1
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBemail_imap\fR
.RS 4
.TS
tab(:);
lt lt
lt lt
lt lt
lt lt
lt lt.
T{
.sp
\fIaddress\fR
T}:T{
.sp
URL of IMAP server
T}
T{
.sp
\fIusername\fR
T}:T{
.sp
Username to authenticate
T}
T{
.sp
\fIpassword\fR
T}:T{
.sp
Password to authenticate
T}
T{
.sp
\fIssl_verify\fR
T}:T{
.sp
Use HTTPS certificate verification
T}
T{
.sp
\fIrefresh_interval\fR
T}:T{
.sp
How often to check for new mail in seconds
T}
.TE
.sp 1
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBexternal_ip\fR
.RS 4
.TS
tab(:);
lt lt
lt lt.
T{
.sp
\fIaddress\fR
T}:T{
.sp
URL to query for IP address
T}
T{
.sp
\fIrefresh_interval\fR
T}:T{
.sp
How often to check address in seconds
T}
.TE
.sp 1
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBmagick_background\fR
.RS 4
.TS
tab(:);
lt lt
lt lt
lt lt.
T{
.sp
\fIblur_radius\fR
T}:T{
.sp
How much blurring to apply
T}
T{
.sp
\fIbrightness\fR
T}:T{
.sp
Brightness level
T}
T{
.sp
\fIsaturation\fR
T}:T{
.sp
Saturation level
T}
.TE
.sp 1
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBnow_playing_mpd\fR
.RS 4
.TS
tab(:);
lt lt
lt lt
lt lt
lt lt.
T{
.sp
\fIhost\fR
T}:T{
.sp
Hostname of mpd server (default: "localhost")
T}
T{
.sp
\fIport\fR
T}:T{
.sp
Port of the server (default: "6600")
T}
T{
.sp
\fItimeout\fR
T}:T{
.sp
How to attempt connecting in ms (default: "5000")
T}
T{
.sp
\fIupdate_interval\fR
T}:T{
.sp
How often to update in ms (default: "1000")
T}
.TE
.sp 1
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBvolume\fR
.RS 4
.TS
tab(:);
lt lt
lt lt.
T{
.sp
\fIcard\fR
T}:T{
.sp
ALSA sound card to use (default: "default")
T}
T{
.sp
\fIselem\fR
T}:T{
.sp
Which ALSA control to adjust (default: "Master")
T}
.TE
.sp 1
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBweather\fR
.RS 4
.TS
tab(:);
lt lt
lt lt
lt lt.
T{
.sp
\fIlocation\fR
T}:T{
.sp
ZIP code of requested location (default: none)
T}
T{
.sp
\fIunit\fR
T}:T{
.sp
Farenheit or Centigrade (default: "c")
T}
T{
.sp
\fIrefresh_interval\fR
T}:T{
.sp
How often to check for updates in s (default: "1800")
T}
.TE
.sp 1
.RE
.SH "FILES"
.PP
\fI~/\&.config/wkline/config\&.json\fR
.RS 4
Per\-user configuration file\&. See
\fBwkline\fR(5) for further details\&.
.RE
.PP
\fI/etc/xdg/wkline/config\&.json\fR
.RS 4
System\-wide configuration file\&. See
\fBwkline\fR(5) for further details\&.
.RE
.SH "AUTHORS"
.sp
Kim Silkebækken <kim\&.silkebaekken@gmail\&.com>
.sp
See https://github\&.com/Lokaltog/wkline/graphs/contributors for a list of all contributors\&.
.SH "SEE ALSO"
.sp
\fBwkline\fR(1)
