.TH WKLINE 1 "March 2014" "beta" "wkline man page"
.SH NAME
wkline \- WebKit-based statusline for tiling window managers
.SH SYNOPSIS
.B wkline [-c
.I config-file
.B ]
.SH DESCRIPTION
.B wkline
is a statusline plugin that launches a plain GTK window with a WebKit WebView
pointing to a static HTML file containing the statusline. It provides a smooth
looking statusline with CSS transitions and effects and the possibility of having a
blurred background without a desktop compositor running.
.SH OPTIONS
.IP "-c config-file"
Use the specified config file. This overrides the system-wide and per-user
configuration files.
.SH FILES
.I /etc/xdg/wkline/config.json
.RS
System-wide configuration file. See
.BR wkline (5)
for further details.
.RE
.I ~/.config/wkline/config.json
.RS
Per-user configuration file. See
.BR wkline (5)
for further details.
.SH ISSUES
See the issue tracker at
.I https://github.com/Lokaltog/wkline/issues
.SH AUTHOR
Kim Silkebækken <kim.silkebaekken@gmail.com>
.SH "SEE ALSO"
.BR wkline (5)
